Import Tensorflow Library

In [2]:
import tensorflow as tf

In [3]:
print("Tensorflow version is", tf.__version__)

Tensorflow version is 2.15.0


Eager Execution

In [4]:
if tf.executing_eagerly():
  print("Eager Execution Enable")
else:
  print("Eager Execution Not Enable")

Eager Execution Enable


GPU CHECK

In [5]:
if tf.test.gpu_device_name():
  print('Default GPU Device Detail: {}'.format(tf.test.gpu_device_name()))
else:
  print('please install GPU based required resources and Tensorflow')

Default GPU Device Detail: /device:GPU:0


In [6]:
!nvidia-smi

Thu Mar 14 08:52:55 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   46C    P0              26W /  70W |    103MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

Constant_tensor

In [5]:
Constant_tensor = tf.constant([[1,2],[3,4]])

In [6]:
print(Constant_tensor)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


Variable_tensor

In [7]:
Variable_tensor = tf.Variable([[5,6],[7,8]])

In [8]:
print(Variable_tensor)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[5, 6],
       [7, 8]], dtype=int32)>


Row Cancatenate

In [9]:
row_concatenate = tf.concat(values=[Constant_tensor,Variable_tensor],axis=0)

In [10]:
print("Row_concatenate:\n",row_concatenate)

Row_concatenate:
 tf.Tensor(
[[1 2]
 [3 4]
 [5 6]
 [7 8]], shape=(4, 2), dtype=int32)


Column Cancatenate

In [11]:
column_concatenate = tf.concat(values=[Constant_tensor,Variable_tensor],axis=1)

In [12]:
print("Column_concatenate:\n",column_concatenate)

Column_concatenate:
 tf.Tensor(
[[1 2 5 6]
 [3 4 7 8]], shape=(2, 4), dtype=int32)


Zero Tensor

In [13]:
zero = tf.zeros(shape=[2,2],dtype=tf.int32)

In [14]:
print("Zero Tensor:\n",zero)

Zero Tensor:
 tf.Tensor(
[[0 0]
 [0 0]], shape=(2, 2), dtype=int32)


One's Tensor

In [15]:
ones = tf.ones(shape=[3,4],dtype=tf.float32)
print("One's Tensor:\n",ones)


One's Tensor:
 tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


Tensor Transpose

In [16]:
tensor_transpose = tf.transpose(Constant_tensor)
print("Tensor Transpose:\n",tensor_transpose)

Tensor Transpose:
 tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)


Type Conversion

In [17]:
tensor_transpose_float = tf.cast(tensor_transpose,tf.float32)
print("Tensor Transpose_Float:\n",tensor_transpose_float)

Tensor Transpose_Float:
 tf.Tensor(
[[1. 3.]
 [2. 4.]], shape=(2, 2), dtype=float32)


Tensor Multiplication

In [18]:
tensor_transpose

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4]], dtype=int32)>

In [19]:
Constant_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [20]:
#NORMAL MULTIPLICATION
multiply_elements = tf.multiply(tensor_transpose,Constant_tensor)
print("multiply_elements:\n",multiply_elements)

multiply_elements:
 tf.Tensor(
[[ 1  6]
 [ 6 16]], shape=(2, 2), dtype=int32)


MATRIX MULTIPLICATION

In [21]:
mat_multiply = tf.matmul(tensor_transpose,Constant_tensor)
print("matrix multiply:\n",mat_multiply)

matrix multiply:
 tf.Tensor(
[[10 14]
 [14 20]], shape=(2, 2), dtype=int32)


TENSOR DETERMINANT

In [22]:
tensor_transpose_float

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 3.],
       [2., 4.]], dtype=float32)>

In [23]:
determinant = tf.linalg.det(tensor_transpose_float)
print(determinant)

tf.Tensor(-2.0, shape=(), dtype=float32)


INVERSE

In [24]:
inverse = tf.linalg.inv(tensor_transpose_float)
print(inverse)

tf.Tensor(
[[-2.   1.5]
 [ 1.  -0.5]], shape=(2, 2), dtype=float32)


IDENTITY MATRIX

In [25]:
identity = tf.eye(num_rows = 3,num_columns = 3,dtype = tf.int32)
print(identity)

tf.Tensor(
[[1 0 0]
 [0 1 0]
 [0 0 1]], shape=(3, 3), dtype=int32)


TENSOR RESHAPE

In [26]:
reshape_con_ten = tf.reshape(tensor = inverse,shape=[1,4])
print(reshape_con_ten)

tf.Tensor([[-2.   1.5  1.  -0.5]], shape=(1, 4), dtype=float32)


NUMPY ARRAY TO TENSOR CONVERSION

In [27]:
import numpy as np
x = np.array([[2,2,3],[1,1,3]])
x

array([[2, 2, 3],
       [1, 1, 3]])

In [28]:
tf.convert_to_tensor(x)

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[2, 2, 3],
       [1, 1, 3]])>